### ISSUE TITLE
Remove insecure and test application functionality

### ISSUE THREAD

**Issue by brylie** [Crowducate/crowducate-platform#119]
Our project has insecure enabled. This has helped us to quickly build the platform, but needs to be removed prior to the 1.0 release.
## Task
- [ ] Remove the insecure package and ensure the application works as expected. 
- [ ] Add issues for any breaking features when insecure is removed. 
  - [ ]  Add any open issues to the 1.0 milestone.

**Comment by sebbel** [comment]
@Rahbaran suggested to move this into the future, but I insist that we change this feature before we go online with a live version.
